## 3. Matric-vector multiplication
<hr>

### 3.1 Example
Example:
$$
\begin{array}{ccccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]  
&\times &
\left[ 
\begin{array}{cccc}
2.7 \\ 
3.5 \\ 
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
4.1\times 2.7 + 5.3\times 3.5\\ 
-3.9\times 2.7 + 8.4\times 3.5 \\ 
6.4\times  2.7  -1.8\times 3.5
\end{array} 
\right]\\
 3 \times 2 && 2 \times 1 &=&  3 \times 1
\end{array} 
$$

Dimension of the matric-vector multiplication operation is given by contraction of $3 \times 2$ with $2 \times 1$ = $3 \times 1$.


### 3.2 Formalization
$$
\begin{array}{ccccc}
\huge[ 
A
]  
&\times &
\huge[ 
x
]
&=& 
\huge[ 
y
]
\\
m \times n && n \times 1 &=&  m \times 1
\end{array}
$$

Element $y_i$ is given by multiplying the $i^{th}$ row of $A$ with vector $x$:

$$
\begin{array}{ccccc}
y_i&=&A_{i}&&x\\
1 \times 1 &=&  1 \times n  &\times&  n \times 1
\end{array}
$$

It is not allowed to multiply a matrix $A$ and a vector $x$ with different $n$ dimensions such as 

$$
\begin{array}{ccccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]  
&\times &
\left[ 
\begin{array}{cccc}
2.7 \\ 
3.5 \\ 
-7.2 \\ 
\end{array} 
\right]
&=&
\quad ?\\
3 \times 2 &\times &  3 \times 1  &=& \textrm{not allowed}
\end{array} 
$$



### Question 3: Multiply the matrix and vector in Python 

In [1]:
import numpy as np


# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
A       = np.array([[1., 2.], [3., 4.], [5., 6.]])
size_A  = np.shape(A)

x       = np.array([[10.], [20.]])
size_x  = np.shape(x)

y       = np.dot(A, x)
size_y  = np.shape(y)
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('A = ')
print(A)
print('******************************')
print('size of A = ')
print(size_A)

print('******************************')
print('x = ')
print(x)
print('******************************')
print('size of x = ')
print(size_x)

print('******************************')
print('y = A x')
print(y)
print('******************************')
print('size of y = ')
print(size_y)
print('******************************')

******************************
A = 
[[1. 2.]
 [3. 4.]
 [5. 6.]]
******************************
size of A = 
(3, 2)
******************************
x = 
[[10.]
 [20.]]
******************************
size of x = 
(2, 1)
******************************
y = A x
[[ 50.]
 [110.]
 [170.]]
******************************
size of y = 
(3, 1)
******************************
