## 4. Matrix-matrix multiplication
<hr>

### 4.1 Example

$$
\begin{array}{ccccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]  
&\times &
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
4.1\times 2.7 + 5.3\times 3.5 & 4.1\times 3.2 + 5.3\times -8.2\\ 
-3.9\times 2.7 + 8.4\times 3.5 & -3.9\times 3.2 + 8.4\times -8.2 \\ 
6.4\times  2.7  -1.8\times 3.5 & 6.4\times  3.2  -1.8\times -8.2
\end{array} 
\right]\\
3 \times 2 &\times &  2 \times 2 &=&  3 \times 2
\end{array}
$$

Dimension of the matrix-matrix multiplication operation is given by contraction of $3 \times 2$ with $2 \times 2$ = $3 \times 2$.


### 4.2 Formalization
$$
\begin{array}{ccccc}
\huge[ 
A
]  
&\times &
\huge[ 
X
]
&=& 
\huge[ 
Y
]
\\
m \times n && n \times p &=&  m \times p
\end{array}
$$

Like for matrix-vector multiplication, matrix-matrix multiplication can be carried out only if $A$ and $X$ have the same $n$ dimension.


### 4.3 Linear algebra operations can be parallelized/distributed
Column $Y_i$ is given by multiplying matrix $A$ with the $i^{th}$ column of $X$:

$$
\begin{array}{ccccc}
Y_i&=&A &\times & X_i\\
1 \times 1 &=&  1 \times n  &\times&  n \times 1
\end{array}
$$

Observe that all columns $X_i$ are independent. Consequently, all columns $Y_i$ are also independent. This allows to vectorize/parallelize linear algebra operations on (multi-core) CPUs, GPUs, clouds, and consequently to solve all linear problems (including linear regression) very efficiently, basically with one single line of code ($Y=AX$ for millions/billions of data). With Moore's law (computers speed increases by 100x every decade), it has introduced a computational revolution in data analysis. 


### Question 4: Multiply the two matrices in Python

In [1]:
import numpy as np

# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
A       = np.array([[1., 2.], [3., 4.], [5., 6.]])
size_A  = np.shape(A)

X       = np.array([[10., 20], [30., 40]])
size_X  = np.shape(X)

Y       = np.dot(A, X)
size_Y  = np.shape(Y)
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('A = ')
print(A)
print('******************************')
print('size of A = ')
print(size_A)

print('******************************')
print('X = ')
print(X)
print('******************************')
print('size of X = ')
print(size_X)

print('******************************')
print('Y = A X')
print(Y)
print('******************************')
print('size of Y = ')
print(size_Y)

******************************
A = 
[[1. 2.]
 [3. 4.]
 [5. 6.]]
******************************
size of A = 
(3, 2)
******************************
X = 
[[10. 20.]
 [30. 40.]]
******************************
size of X = 
(2, 2)
******************************
Y = A X
[[ 70. 100.]
 [150. 220.]
 [230. 340.]]
******************************
size of Y = 
(3, 2)
