## 1. Matrix, vector and scalar representation
<hr>

### 1.1 Matrix 
Example:
$$
x = \left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]
$$

$x_{ij}$ is the element at the $i^{th}$ row and $j^{th}$ column. Here: $x_{11}=4.1,x_{32}=-1.8$.

Dimension of matrix $x$ is the number of rows times the number of columns. <br>
Here $dim(x)=3\times 2$. $x$ is said to be a $3\times 2$ matrix. 

The set of all $3\times 2$ matrices is $\mathbb{R}^{3\times 2}$.


### 1.2 Vector 
Example: 
$$
y = \left[ 
\begin{array}{cccc}
4.1 \\ 
-3.9 \\ 
6.4 
\end{array} 
\right]
$$

$y_i=i^{th}$ element of $y$. Here: $y_1=4.1,y_3=6.4$.

Dimension of vector $y$ is the number of rows. <br>
Here $\rm{dim}(y)=3\times 1$ or $\rm{dim}(y)=3$. $y$ is said to be a 3-dim vector.

The set of all 3-dim vectors is $\mathbb{R}^3$.

### 1.3 Scalar 
Example: 
$$
z=5.6
$$

A scalar has no dimension.

The set of all scalars is $\mathbb{R}$.

Note: $z=[5.6]$ is a 1-dim vector, not a scalar.


### Question 1: Represent matrix, vector and scalar in Python
Hint: You may use numpy library, shape(), type(), dtype.

In [1]:
import numpy as np

# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
x           = np.array([[1., 2., 3.], [4., 5., 6.]])
size_x      = np.shape(x)
type_x      = x.dtype

y           = np.array([1., 2., 3.])
size_y      = np.shape(y)
type_y      = y.dtype

z           = np.array([1.])
size_z      = np.shape(z)
type_z      = z.dtype
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('x = ')
print(x)
print('******************************')
print('size of x = ')
print(size_x)
print('******************************')
print('type of x = ')
print(type_x)

print('******************************')
print('y = ')
print(y)
print('******************************')
print('size of y = ')
print(size_y)
print('******************************')
print('type of y = ')
print(type_y)

print('******************************')
print('z = ')
print(z)
print('******************************')
print('size of z = ')
print(size_z)
print('******************************')
print('type of z = ')
print(type_z)
print('******************************')

******************************
x = 
[[1. 2. 3.]
 [4. 5. 6.]]
******************************
size of x = 
(2, 3)
******************************
type of x = 
float64
******************************
y = 
[1. 2. 3.]
******************************
size of y = 
(3,)
******************************
type of y = 
float64
******************************
z = 
[1.]
******************************
size of z = 
(1,)
******************************
type of z = 
float64
******************************
