## 5. Some linear algebra properties
<hr>

### 5.1 Matrix multiplication is *not* commutative

$$
\begin{array}{ccccccc}
A &\times& B &\not=& B &\times& A\\
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]  
&\times &
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&\not=&
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&\times &
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]
\end{array} 
$$



### 5.2 Scalar multiplication is associative

$$
\begin{array}{ccccccc}
\alpha &\times& B &=& B &\times& \alpha\\
4.1  &\times&
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
2.7 & 3.2 \\ 
3.5 & -8.2 \\ 
\end{array} 
\right]
&\times&
4.1
\end{array}
$$



### 5.3 Transpose matrix

$$
\begin{array}{ccccc}
X^T_{ij} &=& X_{ji}\\
\left[ 
\begin{array}{cccc}
2.7 & 3.2 & 5.4 \\ 
3.5 & -8.2 & -1.7\\ 
\end{array} 
\right]^T
&=&
\left[ 
\begin{array}{cccc}
2.7 & 3.5\\
3.2 & -8.2 \\ 
5.4 & -1.7\\ 
\end{array} 
\right]
\end{array}
$$



### 5.4 Identity matrix

$$
I=I_{n}=Diag([1,1,...,1])
$$

such that

$$
I\times A = A \times I
$$

Examples:
$$
I_2=
\left[ 
\begin{array}{cccc}
1 & 0\\
0 & 1  
\end{array} 
\right]
$$

$$
I_3=
\left[ 
\begin{array}{cccc}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1  
\end{array} 
\right]
$$


### 5.5 Matrix inverse

For any square $n\times n$ matrix $A$, the matrix inverse $A^{-1}$ is defined as

$$
AA^{-1} = A^{-1}A = I
$$

Example:

$$
\begin{array}{ccccc}
\left[ 
\begin{array}{cccc}
2.7 & 3.5\\
3.2 & -8.2 
\end{array} 
\right]
&\times &
\left[ 
\begin{array}{cccc}
0.245 & 0.104 \\ 
0.095 & -0.080
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
1 & 0\\
0 & 1  
\end{array} 
\right]\\
A&\times &A^{-1} &=& I
\end{array}
$$


Some matrices do not hold an inverse such as zero matrices. They are called degenerate or singular.

### Question 5: Compute the matrix transpose in Python. Determine also the matrix inverse in Python.

In [1]:
import numpy as np

# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
A                   = np.array([[1., 2.], [3., 4.]])
size_A              = np.shape(A)

AT                  = A.T
size_AT             = np.shape(AT)

mul_AT_A            = np.dot(AT, A)
size_mul_AT_A       = np.shape(mul_AT_A)

invA                = np.linalg.inv(A)
size_invA           = np.shape(invA)

inv_mul_AT_A        = np.linalg.inv(mul_AT_A)
size_inv_mul_AT_A   = np.shape(inv_mul_AT_A )
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('A = ')
print(A)
print('******************************')
print('size of A = ')
print(size_A)

print('******************************')
print('AT = transpose of A ')
print(AT)
print('******************************')
print('size of AT = ')
print(size_AT)

print('******************************')
print('AT A = multiplication of AT and A')
print(mul_AT_A)
print('******************************')
print('size of multiplication of AT and A = ')
print(size_mul_AT_A)

print('******************************')
print('inverse of A = ')
print(invA)
print('******************************')
print('size of inverse of A = ')
print(size_invA)

print('******************************')
print('inverse of multiplication of A transpose and A = ')
print(inv_mul_AT_A)
print('******************************')
print('size of inverse of multiplication of A transpose and A = ')
print(size_inv_mul_AT_A)
print('******************************')

******************************
A = 
[[1. 2.]
 [3. 4.]]
******************************
size of A = 
(2, 2)
******************************
AT = transpose of A 
[[1. 3.]
 [2. 4.]]
******************************
size of AT = 
(2, 2)
******************************
AT A = multiplication of AT and A
[[10. 14.]
 [14. 20.]]
******************************
size of multiplication of AT and A = 
(2, 2)
******************************
inverse of A = 
[[-2.   1. ]
 [ 1.5 -0.5]]
******************************
size of inverse of A = 
(2, 2)
******************************
inverse of multiplication of A transpose and A = 
[[ 5.  -3.5]
 [-3.5  2.5]]
******************************
size of inverse of multiplication of A transpose and A = 
(2, 2)
******************************
