## 2. Matrix addition and scalar-matrix multiplication
<hr>

### 2.1 Matrix addition
Example:
$$
\begin{array}{ccccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right] & + & 
\left[ 
\begin{array}{cccc}
2.7 & 7.3\\ 
3.5 & 2.4 \\ 
6.0 & -1.1
\end{array} 
\right]
& = &
\left[ 
\begin{array}{cccc}
4.1+2.7 & 5.3+7.3\\ 
-3.9+3.5 & 8.4+2.4 \\ 
6.4+6.0 & -1.8-1.1
\end{array} 
\right]\\
3 \times 2 &+& 3 \times 2 &=& 3 \times 2
\end{array} 
$$

All matrix and vector operations must satisfy dimensionality properties. For example, it is not allowed to add two matrices of different dimentionalities, such as

$$
\begin{array}{ccccc}
\left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right] & + & 
\left[ 
\begin{array}{cccc}
2.7 & 7.3 & 5.0\\ 
3.5 & 2.4 & 2.8 \\ 
\end{array} 
\right]
& = &
\textrm{Not allowed}\\ 
3 \times 2 &+& 2 \times 3 &=& \textrm{Not allowed}
\end{array} 
$$




### 2.1 Scalar-matrix multiplication
Example:
$$
\begin{array}{ccccc}
3 &\times& \left[ 
\begin{array}{cccc}
4.1 & 5.3\\ 
-3.9 & 8.4 \\ 
6.4 & -1.8
\end{array} 
\right]
&=&
\left[ 
\begin{array}{cccc}
3 \times 4.1 & 3 \times 5.3\\ 
3 \times -3.9 & 3 \times 8.4 \\ 
3 \times 6.4 & 3 \times  -1.8
\end{array} 
\right]\\
\textrm{No dim} &+& 3 \times 2 &=& 3 \times 2
\end{array} 
$$


### Question 2: Add the two matrices, and perform the multiplication scalar-matrix in Python

In [1]:
import numpy as np

# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
x           = np.array([[1., 2., 3.], [4., 5., 6.]])
size_x      = np.shape(x)

y           = np.array([[10., 20., 30.], [40., 50., 60.]])
size_y      = np.shape(y)

z           = np.array([2.])
size_z      = np.shape(z)

sum_x_y     = x + y
mul_x_z     = x*z
div_x_z     = x/z

size_sum_x_y    = np.shape(sum_x_y)
size_mul_x_z    = np.shape(mul_x_z)
size_div_x_z    = np.shape(div_x_z)
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('x = ')
print(x)
print('******************************')
print('size of x = ')
print(size_x)

print('******************************')
print('y = ')
print(y)
print('******************************')
print('size of y = ')
print(size_y)

print('******************************')
print('z = ')
print(z)
print('******************************')
print('size of z = ')
print(size_z)

print('******************************')
print('x + y = ')
print(sum_x_y)
print('******************************')
print('size of x + y = ')
print(size_sum_x_y)

print('******************************')
print('x * z = ')
print(mul_x_z)
print('******************************')
print('size of x * z = ')
print(size_mul_x_z)

print('******************************')
print('x / z = ')
print(div_x_z)
print('******************************')
print('size of x / z = ')
print(size_div_x_z)
print('******************************')

******************************
x = 
[[1. 2. 3.]
 [4. 5. 6.]]
******************************
size of x = 
(2, 3)
******************************
y = 
[[10. 20. 30.]
 [40. 50. 60.]]
******************************
size of y = 
(2, 3)
******************************
z = 
[2.]
******************************
size of z = 
(1,)
******************************
x + y = 
[[11. 22. 33.]
 [44. 55. 66.]]
******************************
size of x + y = 
(2, 3)
******************************
x * z = 
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
******************************
size of x * z = 
(2, 3)
******************************
x / z = 
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
******************************
size of x / z = 
(2, 3)
******************************
